/*
 * The shared icon vocabulary. Geometry comes from Lucide (ISC License); each
 * app renders these nodes with its own <Icon> component so the website and
 * the client draw identical glyphs.
 */
import {
  ArchiveRestore,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Building,
  Camera,
  Check,
  ChevronDown,
  CircleAlert,
  CircleCheck,
  ClipboardCheck,
  ClipboardList,
  Copy,
  CreditCard,
  Download,
  EllipsisVertical,
  File,
  FileText,
  FolderOpen,
  type IconNode,
  Image,
  Inbox,
  Info,
  KeyRound,
  Landmark,
  Layers,
  ListChecks,
  Lock,
  LogOut,
  Mail,
  Menu,
  Paperclip,
  Pencil,
  Plus,
  RefreshCw,
  Search,
  Shield,
  ShieldCheck,
  Trash,
  TriangleAlert,
  Unlink,
  Upload,
  UserPlus,
  Users,
  X,
} from "lucide";

export const icons = {
  add: Plus,
  alert: TriangleAlert,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  attachment: Paperclip,
  audits: ClipboardCheck,
  billing: CreditCard,
  businesses: Building,
  camera: Camera,
  check: Check,
  checklist: ListChecks,
  chevronDown: ChevronDown,
  close: X,
  copy: Copy,
  document: FileText,
  download: Download,
  edit: Pencil,
  error: CircleAlert,
  external: ArrowUpRight,
  file: File,
  finance: Landmark,
  image: Image,
  inbox: Inbox,
  info: Info,
  issues: ClipboardList,
  key: KeyRound,
  layers: Layers,
  library: FolderOpen,
  lock: Lock,
  mail: Mail,
  menu: Menu,
  more: EllipsisVertical,
  organization: Users,
  refresh: RefreshCw,
  restore: ArchiveRestore,
  search: Search,
  security: ShieldCheck,
  shield: Shield,
  signOut: LogOut,
  success: CircleCheck,
  trash: Trash,
  unlink: Unlink,
  upload: Upload,
  userAdd: UserPlus,
} satisfies Record<string, IconNode>;

export type IconName = keyof typeof icons;
