/*
 * The shared icon vocabulary. Geometry comes from Lucide (ISC License); each
 * app renders these nodes with its own <Icon> component so the website and
 * the client draw identical glyphs.
 */
import {
  ArchiveRestore,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Building,
  Camera,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  ClipboardCheck,
  ClipboardList,
  Copy,
  Download,
  EllipsisVertical,
  FileText,
  Folder,
  FolderInput,
  FolderOpen,
  FolderPlus,
  type IconNode,
  Image,
  Inbox,
  Info,
  KeyRound,
  Landmark,
  Laptop,
  Layers,
  Link,
  ListChecks,
  Lock,
  LogOut,
  Mail,
  Menu,
  Monitor,
  MonitorSmartphone,
  Paperclip,
  Pencil,
  Plus,
  RefreshCw,
  Search,
  Shield,
  ShieldCheck,
  Smartphone,
  Trash,
  TriangleAlert,
  Unlink,
  Upload,
  UserPlus,
  Users,
  X,
} from "lucide";

export const icons = {
  add: Plus,
  alert: TriangleAlert,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  attachment: Paperclip,
  audits: ClipboardCheck,
  businesses: Building,
  cellPhone: Smartphone,
  camera: Camera,
  check: Check,
  checklist: ListChecks,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  close: X,
  computer: Laptop,
  copy: Copy,
  document: FileText,
  download: Download,
  edit: Pencil,
  equipment: MonitorSmartphone,
  error: CircleAlert,
  external: ArrowUpRight,
  finance: Landmark,
  folder: Folder,
  folderAdd: FolderPlus,
  image: Image,
  inbox: Inbox,
  info: Info,
  issues: ClipboardList,
  key: KeyRound,
  layers: Layers,
  library: FolderOpen,
  link: Link,
  lock: Lock,
  mail: Mail,
  menu: Menu,
  monitor: Monitor,
  more: EllipsisVertical,
  move: FolderInput,
  organization: Users,
  refresh: RefreshCw,
  restore: ArchiveRestore,
  search: Search,
  security: ShieldCheck,
  shield: Shield,
  signOut: LogOut,
  success: CircleCheck,
  trash: Trash,
  unlink: Unlink,
  upload: Upload,
  userAdd: UserPlus,
} satisfies Record<string, IconNode>;

export type IconName = keyof typeof icons;
