#!/bin/sh

set -e

REPO_ROOT="$(git rev-parse --show-toplevel)"
MESSAGE_FILE="$1"

cd "$REPO_ROOT"

echo "Linting commit message..."
bunx commitlint --config "$REPO_ROOT/commitlint.config.mts" --edit "$MESSAGE_FILE"
